[project]
name = "esolangs"
version = "0.1.0"
description = "Esoteric language interpreters"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
